# -*- coding: utf-8 -*-
"""BFS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nj-zsigxyvP50PP5QjdFqxsMXlYyYf2I
"""

import collections

class Graph:
    def __init__(self):  # Corrected constructor
        self.graph = collections.defaultdict(list)

    def addEdge(self, u, v):
        self.graph[u].append(v)

    def BFS(self, start, goal):
        visited, queue = set(), collections.deque([(start, [start])])
        visited.add(start)

        while queue:
            vertex, path = queue.popleft()
            print(vertex, end=' ')  # Print visit order

            if vertex == goal:
                print("\nJalur ditemukan:", " -> ".join(path))
                return

            for neighbour in self.graph[vertex]:
                if neighbour not in visited:
                    visited.add(neighbour)
                    queue.append((neighbour, path + [neighbour]))

        print(f"\nTidak ada jalur dari {start} ke {goal}")

if __name__ == "__main__":  # Corrected main check
    g = Graph()
    g.addEdge('A', 'S')
    g.addEdge('A', 'B')
    g.addEdge('S', 'F')
    g.addEdge('S', 'G')
    g.addEdge('B', 'H')
    g.addEdge('G', 'D')

    print("BFS mencari jalur dari A ke H:")
    g.BFS('A', 'H')